# footer:
  # framework: Framework
  # theme: Theme

# copy:
  # success: Copy successfully
  # error: Copy error
  # noSupport: The browser does not support

# page:
  # articles: Articles
  # tag: Tag
  # category: Category
  # archives: Archives

# sticky: Sticky
# no_title: No title

# post:
  # created: Created
  # updated: Updated
  # wordcount: Word count
  # min2read: Reading time
  # min2read_unit: min
  # page_pv: Post View
  # comments: Comments
  # copyright:
    # author: Author
    # link: Link
    # copyright_notice: Copyright Notice
    # copyright_content: 'All articles in this blog are licensed under <a href="%s">%s</a> unless stating additionally.'
  # recommend: Related Articles

# search: Search
# algolia_search:
  # input_placeholder: Search for Posts
  # hits_empty: "We didn't find any results for the search: ${query}."
  # hits_stats: '${hits} results found in ${time} ms'

# local_search:
  # label: Local search
  # input_placeholder: Search for Posts
  # hits_empty: "We didn't find any results for the search: ${query}"

# pagination:
  # prev: Previous Post
  # next: Next Post

# comment: Comment

# aside:
  # articles: Articles
  # tags: Tags
  # categories: Categories
  # card_announcement: Announcement
  # card_categories: Categories
  # card_tags: Tags
  # card_archives: Archives
  # card_recent_post: Recent Post
  # card_webinfo:
    # headline: Info
    # article_name: Article
    # runtime:
      # name: Run time
      # unit: days
    # last_push_date:
      # name: Last Push
    # site_wordcount: Total Count
    # site_uv_name: UV
    # site_pv_name: PV
  # more_button: More
  # card_newest_comments:
    # headline: Newest Comments
    # loading_text: loading...
    # error: Unable to get the data, please make sure the settings are correct.
    # zero: No Comment
  # card_toc: Catalog

# date_suffix:
  # just: Just
  # min: minutes ago
  # hour: hours ago
  # day: days ago
  # month: months ago

# donate: Donate
# share: Share

# rightside:
  # readmode_title: Read Mode
  # font_plus_title: Increase font size
  # font_minus_title: Decrease font size
  # translate_title: Toggle Between Traditional Chinese And Simplified Chinese
  # night_mode_title: Toggle Between Light And Dark Mode
  # back_to_top: Back To Top
  # toc: Table Of Contents
  # scroll_to_comment: Scroll To Comments
  # setting: Setting
  # aside: Toggle between single-column and double-column

# copy_copyright:
  # author: Author
  # link: Link
  # source: Source
  # info: Copyright is owned by the author. For commercial reprints, please contact the author for authorization. For non-commercial reprints, please indicate the source.

# Snackbar:
  # chs_to_cht: Traditional Chinese Activated Manually
  # cht_to_chs: Simplified Chinese Activated Manually
  # day_to_night: Dark Mode Activated Manually
  # night_to_day: Light Mode Activated Manually

# loading: Loading...

# error404:
  # error_title: Page not found
  # back_button: Go back home
footer:
  framework: 框架
  theme: 主题

copy:
  success: 复制成功
  error: 复制错误
  noSupport: 浏览器不支持

page:
  articles: 文章总览
  tag: 标签
  category: 分类
  archives: 归档

sticky: 置顶
no_title: 无题

post:
  created: 发表于
  updated: 更新于
  wordcount: 字数总计
  min2read: 阅读时长
  min2read_unit: 分钟
  page_pv: 阅读量
  comments: 评论数
  copyright:
    author: 文章作者
    link: 文章链接
    copyright_notice: 版权声明
    copyright_content: '本博客所有文章除特别声明外，均采用
      <a href="%s" target="_blank">%s</a> 许可协议。转载请注明来自 <a href="%s" target="_blank">%s</a>！'
  recommend: 相关推荐

search: 搜索
algolia_search:
  input_placeholder: 搜索文章
  hits_empty: '找不到您查询的内容：${query}'
  hits_stats: '找到 ${hits} 条结果，用时 ${time} 毫秒'

local_search:
  label: 本地搜索
  input_placeholder: 搜索文章
  hits_empty: '找不到您查询的内容：${query}'

pagination:
  prev: 上一篇
  next: 下一篇

comment: 评论

aside:
  articles: 文章
  tags: 标签
  categories: 分类
  card_announcement: 公告
  card_pixiv: Pixiv日榜Top50
  card_calendar: 日历
  card_categories: 分类
  card_tags: 标签
  card_archives: 归档
  card_recent_post: 最新文章
  card_ip: 当前访问用户
  card_webinfo:
    headline: 网站资讯
    article_name: 文章数目
    runtime:
      name: 已运行时间
      unit: 天
    last_push_date:
      name: 最后更新时间
    site_wordcount: 本站总字数
    site_uv_name: 本站访客数
    site_pv_name: 本站总访问量
  more_button: 查看更多
  card_newest_comments:
    headline: 最新评论
    loading_text: 正在加载中...
    error: 无法获取评论，请确认相关配置是否正确
    zero: 没有评论
  card_toc: 目录

date_suffix:
  just: 刚刚
  min: 分钟前
  hour: 小时前
  day: 天前
  month: 个月前

donate: 打赏
share: 分享

rightside:
  readmode_title: 阅读模式
  font_plus_title: 放大字体
  font_minus_title: 缩小字体
  translate_title: 简繁转换
  night_mode_title: 浅色和深色模式转换
  back_to_top: 回到顶部
  toc: 目录
  scroll_to_comment: 直达评论
  setting: 设置
  aside: 单栏和双栏切换

copy_copyright:
  author: 作者
  link: 链接
  source: 来源
  info: 著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

Snackbar:
  chs_to_cht: 你已切换为繁体
  cht_to_chs: 你已切换为简体
  day_to_night: 你已切换为深色模式
  night_to_day: 你已切换为浅色模式

loading: 加载中...

error404:
  error_title: 页面没有找到
  back_button: 回到主页
